### PR TITLE
dollar.py script applied

### PR DESCRIPTION
**Pull request by alanwilter**
My best try to get $() to replace `` whatever it matters

### CODE REVIEW

**Comment by yousefvand** [comment]
Thanks for your contribution, since `$` has a special meaning in `snippets` it needs to be escaped (`$ -> \\$`). At some point project was getting complicated so an abstract layer was added (`build.js`) for generating `snippets.json` and `COMMANDS.md`. There's no need to change any other files out of `nsroot` since `build.js` handles the rest. BTW unfortunately `build.js` doesn't work on Windows systems. If changes are restricted to `nsroot` directory the `PR` can be merged (I'll take care of build part).

**Comment by alanwilter** [comment]
First, thanks a lot for what you've done, `shellman` is absolutely fantastic.

Now, I knew I would have forgotten something, always something :-D.

The truth is I didn't tested it, I was afraid to mess up my VS Code setup (I've just started using it).

Anyway, would like me to correct the code so to get (`$ -> \\$`)? And if I understand well, this change should only be applied to the files under `nsroot`, right?

**Comment by alanwilter** [comment]
BTW, my script had changed `samples/backup-tool/backup.sh`, which I guess is OK.

**Comment by yousefvand** [comment]
>  would you like me to correct the code so to get ($ -> \\$)? And if I understand well, this change should only be applied to the files under nsroot, right?

Yes to both questions.

> my script had changed samples/backup-tool/backup.sh, which I guess is OK

Yes it's ok.

**Comment by alanwilter** [comment]
I'm closing this one and creating another, correct, hopefully, PR.

**Pull request closed without merging**
